[package]
name = "trappist"
version = "1.0.0"
authors = ["Trappist Network <https://github.com/TrappistNetwork>"]
description = "A versatile Proof-of-Authority (PoA) Blockchain network."
license = "Unlicense"
homepage = "https://trappist.io"
repository = "https://github.com/TrappistNetwork/trappist"
edition = "2021"
build = "build.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/arturgontijo/substrate", branch = "master" }

[[bin]]
name = "trappist-collator"
path = "src/main.rs"

[dependencies]
async-trait = "0.1.57"
clap = { version = "3.2.17", features = ["derive"] }
derive_more = "0.99.2"
log = "0.4.17"
codec = { package = "parity-scale-codec", version = "3.0.0" }
serde = { version = "1.0.140", features = ["derive"] }
hex-literal = "0.3.4"
futures = { version = "0.3.1", features = ["compat"] }

# RPC related Dependencies
jsonrpsee-core = "0.15.1"

# Local Dependencies
trappist-runtime = { path = "../runtime" }

# Substrate Dependencies
frame-benchmarking = { git = "https://github.com/arturgontijo/substrate", branch = "master" }
frame-benchmarking-cli = { git = "https://github.com/arturgontijo/substrate", branch = "master" }
try-runtime-cli = { git = "https://github.com/arturgontijo/substrate", branch = "master" }

pallet-transaction-payment-rpc = { git = "https://github.com/arturgontijo/substrate", branch = "master" }
pallet-contracts-rpc =  { version = "4.0.0-dev", git = "https://github.com/arturgontijo/substrate.git",  branch = "master" }

substrate-frame-rpc-system = { git = "https://github.com/arturgontijo/substrate", branch = "master" }
substrate-prometheus-endpoint = { git = "https://github.com/arturgontijo/substrate", branch = "master" }

## Substrate Client Dependencies
sc-basic-authorship = { git = "https://github.com/arturgontijo/substrate", branch = "master" }
sc-chain-spec = { git = "https://github.com/arturgontijo/substrate", branch = "master" }
sc-cli = { git = "https://github.com/arturgontijo/substrate", features = ["wasmtime"], branch = "master" }
sc-client-api = { git = "https://github.com/arturgontijo/substrate", branch = "master" }
sc-consensus = { git = "https://github.com/arturgontijo/substrate", branch = "master" }
sc-executor = { git = "https://github.com/arturgontijo/substrate", features = ["wasmtime"], branch = "master" }
sc-network = { git = "https://github.com/arturgontijo/substrate", branch = "master" }
sc-network-common = { git = "https://github.com/arturgontijo/substrate", branch = "master" }
sc-keystore = { git = "https://github.com/arturgontijo/substrate", branch = "master" }
sc-rpc = { git = "https://github.com/arturgontijo/substrate", branch = "master" }
sc-rpc-api = { git = "https://github.com/arturgontijo/substrate", branch = "master" }
sc-service = { git = "https://github.com/arturgontijo/substrate", features = ["wasmtime"], branch = "master" }
sc-sysinfo = { git = "https://github.com/arturgontijo/substrate", branch = "master" }
sc-telemetry = { git = "https://github.com/arturgontijo/substrate", branch = "master" }
sc-transaction-pool = { git = "https://github.com/arturgontijo/substrate", branch = "master" }
sc-transaction-pool-api = { git = "https://github.com/arturgontijo/substrate", branch = "master" }
sc-tracing = { git = "https://github.com/arturgontijo/substrate", branch = "master" }

## Substrate Primitive Dependencies
sp-api = { git = "https://github.com/arturgontijo/substrate", branch = "master" }
sp-block-builder = { git = "https://github.com/arturgontijo/substrate", branch = "master" }
sp-blockchain = { git = "https://github.com/arturgontijo/substrate", branch = "master" }
sp-consensus = { git = "https://github.com/arturgontijo/substrate", branch = "master" }
sp-consensus-aura = { git = "https://github.com/arturgontijo/substrate", branch = "master" }
sp-core = { git = "https://github.com/arturgontijo/substrate", branch = "master" }
sp-inherents = { git = "https://github.com/arturgontijo/substrate", branch = "master" }
sp-io = { git = "https://github.com/arturgontijo/substrate", branch = "master" }
sp-keystore = { git = "https://github.com/arturgontijo/substrate", branch = "master" }
sp-offchain = { git = "https://github.com/arturgontijo/substrate", branch = "master" }
sp-runtime = { git = "https://github.com/arturgontijo/substrate", branch = "master" }
sp-session = { git = "https://github.com/arturgontijo/substrate", branch = "master" }
sp-timestamp = { git = "https://github.com/arturgontijo/substrate", branch = "master" }
sp-transaction-pool = { git = "https://github.com/arturgontijo/substrate", branch = "master" }

# Cumulus dependencies
cumulus-client-cli = { git = "https://github.com/arturgontijo/cumulus", branch = "trappist-xcm-v3" }
cumulus-client-consensus-aura = { git = "https://github.com/arturgontijo/cumulus", branch = "trappist-xcm-v3" }
cumulus-client-consensus-relay-chain = { git = "https://github.com/arturgontijo/cumulus", branch = "trappist-xcm-v3" }
cumulus-client-consensus-common = { git = "https://github.com/arturgontijo/cumulus", branch = "trappist-xcm-v3" }
cumulus-client-network = { git = "https://github.com/arturgontijo/cumulus", branch = "trappist-xcm-v3" }
cumulus-client-service = { git = "https://github.com/arturgontijo/cumulus", branch = "trappist-xcm-v3" }
cumulus-primitives-core = { git = "https://github.com/arturgontijo/cumulus", branch = "trappist-xcm-v3" }
cumulus-primitives-parachain-inherent = { git = "https://github.com/arturgontijo/cumulus", branch = "trappist-xcm-v3" }
cumulus-relay-chain-inprocess-interface = { git = "https://github.com/arturgontijo/cumulus", branch = "trappist-xcm-v3" }
cumulus-relay-chain-interface = { git = "https://github.com/arturgontijo/cumulus", branch = "trappist-xcm-v3" }
cumulus-relay-chain-rpc-interface = { git = "https://github.com/arturgontijo/cumulus", branch = "trappist-xcm-v3" }

parachains-common = { git = "https://github.com/arturgontijo/cumulus", branch = "trappist-xcm-v3", default-features = false }

# Polkadot dependencies
polkadot-cli = { git = "https://github.com/arturgontijo/polkadot", branch = "trappist-xcm-v3" }
polkadot-parachain = { git = "https://github.com/arturgontijo/polkadot", branch = "trappist-xcm-v3" }
polkadot-primitives = { git = "https://github.com/arturgontijo/polkadot", branch = "trappist-xcm-v3" }
polkadot-service = { git = "https://github.com/arturgontijo/polkadot", branch = "trappist-xcm-v3" }
xcm = { git = "https://github.com/arturgontijo/polkadot", default-features = false, branch = "trappist-xcm-v3" }

[dev-dependencies]
assert_cmd = "2.0"
nix = "0.23"
tempfile = "3.2.0"

[features]
default = []
runtime-benchmarks = [
    "trappist-runtime/runtime-benchmarks"
]
try-runtime = [
	"trappist-runtime/try-runtime"
]
